// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  staging: true,
  hmr: false,
  version: env.npm_package_version + '-staging',
  serverUrl: '', // Configure your staging API URL
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  sentryDsn: 'https://832c8cecea97174220ae89225b8fce60@o4510549056487424.ingest.us.sentry.io/4510549057798144',
};
